### ISSUE TITLE
Sitepress data file API

### ISSUE THREAD

**Issue by bradgessler** [sitepress/sitepress#19]
Have a data file API like https://middlemanapp.com/advanced/data-files/ and https://www.bridgetownrb.com/docs/datafiles

This should probably be released as a separate gem (I'm going to be shocked if one doesn't exist) because it's still that static site generators always have to re-invent this. Be sure to do some research to see if a gem already exists for this before rolling something custom.

**Comment by bradgessler** [comment]
Code will end up looking something like this:

```ruby
def data(dataset)
  path = Sitepress.site.root_path.join("data", "#{dataset}.yml")
  data = YAML.load_file(path)
  
  case data
  when Hash
    OpenStruct.new(data)
  when Array
    data.map { |h| OpenStruct.new(h) }
  end
end
```

It should include the file extension though so the parser doesn't have to guess if its yml, JSON, csv, or whatever.

**Comment by bradgessler** [comment]
I have a `date_helper.rb` file that mimics Middleman, which I'm not sure I'm going to do yet. Here it is for posterity:

```ruby
module DataHelper
  def dataset(key)
    path = Sitepress.site.root_path.join("data", "#{key}.yml")
    Sitepress::Data.manage(YAML.load_file(path))
  end

  def data
    keys = Dir.glob("data/*.yml").map do |path|
      File.basename(path, ".yml").to_sym
    end

    Struct.new(*keys).new(*keys.map{|key| dataset(key) })
  end
end
```

I still think I prefer a file data helper that looks like this:

```ruby
data("people.yml")
```

This makes it possible to have other formats, like `yml`, `toml`, `json`, etc.

**Comment by joemasilotti** [comment]
Fair point on not using YAML files. I personally don't care as I only have a handful of data and it is all YAML from Jekyll.

That said, this now creates an inconsistent API with the frontmatter API in #16. I'm using the following to convert YAML to JSON then load it as an Open Struct. It works great for root level hashes. But it is a tad weird when you want to iterate over a root level array.

```ruby
module DataHelper
  def data(dataset)
    path = Sitepress.site.root_path.join("data", "#{dataset}.yml")
    JSON.parse(YAML.load_file(path).to_json, object_class: OpenStruct)
  end
end
```

**Comment by bradgessler** [comment]
Yeah I got rid OStruct and replaced with `Sitepress::Data.manage()`. You can pass it an array or hash and it shouldn't be weird — if it is weird, it's a bug.

To get access to that, you'll have to point the Sitepress gem to:

```ruby
gem "sitepress", "~> 3.2", github: "sitepress/sitepress", branch: "version-4"
```

**Comment by joemasilotti** [comment]
I might be missing something, but I can't get an array to work. A root-level hash works great.

I'm using the `version-4` branch with your helper above copy-pasted in.

```yaml
# data/projects.yml
- name: RailsDevs
  description: The reverse job board exclusively for Ruby on Rails developers. An open source app.
  link:
    href: https://railsdevs.com
    label: railsdevs.com
  logo: railsdevs.png

- name: ⚡️ Hotwire dev newsletter
  description: Monthly link roundup of the latest Hotwire articles, code, courses, and more.
  link:
    href: /hotwire
    label: masilotti.com
  logo: newsletter.png

# ...snip...
```

```ruby
data.projects.count # => 0
data.projects.first # => nil
data.projects.map(&:name) # => [] 
```
